### ISSUE TITLE
Update dependencies to new `flutter_web_bluetooth` 1.0.0

### ISSUE THREAD

**Issue by vovagorodok** [Navideck/universal_ble#101]
Package `flutter_web_bluetooth` now has 1.0.0 version! Will be nice to have updated dependencies

**Comment by fotiDim** [comment]
Updated on main. We will have a new release within the week.

**Comment by fotiDim** [comment]
Released in [0.14.0](https://pub.dev/packages/universal_ble/versions/0.14.0)
