### ISSUE TITLE
Packets fragmentation

### ISSUE THREAD

**Issue by daniele-fochesato** [Navideck/universal_ble#116]
Hi everyone, i'm building an app to send fragmented packets but when i try to send them using "writeValue" it returns an error (Unknown ATT error) or it goes on timeout. I tried to add a simple delay on each write request but it doesn't solve the problem.

Here's the simple code:
`
await UniversalBle.connect(widget.deviceId);
await UniversalBle.discoverServices(widget.deviceId);

// fixed value for testing
String value = 'big json';

// convert the string to bytes and retrieve fragments
List<List<int>> fragments = _fragmentData(Uint8List.fromList(value.codeUnits), 20);
inspect(fragments);

// write the values
for (int i = 0; i < fragments.length; i++) {
        await UniversalBle.writeValue(widget.deviceId, widget.serviceUuid, widget.characteristic.uuid, 
        Uint8List.fromList(fragments[i]), BleOutputProperty.withResponse);
        await Future.delayed(const Duration(milliseconds: 300)); 
}

// disconnect the device
await UniversalBle.disconnect(widget.deviceId);
`

Have you ever faced this type of issue? What am i doing wrong?

Thanks.

**Comment by Sravdar** [comment]
You don't need to add delay as writeValue with withResponse property waits for response or error before returning.

As for the problem itself i would like to help but can you give details of the device you are using and device you are trying to connect? Have you tried to communicate with the device with other methods (like python on windows)? When you log `onAvailabilityChange` and `onConnectionChange` results do you see it working as expected?
