### ISSUE TITLE
Error when building for windows

### ISSUE THREAD

**Issue by mortenboye** [Navideck/universal_ble#14]
When using Universal_ble in my project i can't build for Windows desktop.

Instead i get this error:

`C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6006: "CL.exe" exited with code -1073741819. [C:\Users\blablabla\build\windows\x64\plugins\universal_ble\universal_ble_plugin.vcxproj]`

Any ideas as to why this happens?

**Comment by fotiDim** [comment]
I tested the example app and a new project with the universal_ble dependency in:
Win 10 22H2 - VS 2022 17.9.2 - Flutter 3.19.1
Win 11 23H2 - VS 2022 17.9.2 - Flutter 3.19.1
and they compile just fine.

Make sure to clone the latest version of the project. Try a `flutter clean` in the example folder and then `flutter run`.

**Comment by mortenboye** [comment]
I tried to build the example app from a fresh clone from git and got the same error:

```PS C:\Users\Morten\Code\universal_ble\example> flutter build windows

C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6006: "CL.exe" exited with code -1073741819. [C:\Users\Morten\Code\universal_ble\example\build\windows\x64\plugins\universal_ble\universal_ble_plugin.vcxproj]
Building Windows application...                                    51.5s
Build process failed.```

**Comment by fotiDim** [comment]
Thank you for the logs. Can you also post the output of `flutter doctor -v`?
On this machine are you able to build other Flutter projects?

**Comment by mortenboye** [comment]
Flutter doctor:

```
PS C:\Users\Morten\Code\universal_ble> flutter doctor -v
[√] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.22631.3155], locale en-US)
    • Flutter version 3.19.0 on channel stable at C:\Users\Morten\Code\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (2 weeks ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Morten\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34607.119
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.87.0)
    • VS Code at C:\Users\Morten\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3155]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 122.0.6261.70
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.52

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

Creating a new Flutter Project compiles and builds fine on windows.

Thank you for the link. I've also found this which points in a similar direction:

> The exit code -1073741819 in hex is 0xC0000005. If you look up this code in Microsoft's documentation ([NTSTATUS Values](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55)) you will see that it indicates that your program was terminated due to an access violation. This error can occur for a variety of reasons, including de-referencing a NULL pointer or referencing an invalid address.

from [here](https://learn.microsoft.com/en-us/answers/questions/379441/error-code-exited-with-code-1073741819)

**Comment by fotiDim** [comment]
@mortenboye based on what I read [here](https://stackoverflow.com/a/40672993/2700613) the error is within the compiler itself. Can you try upgrading Flutter to 3.19.1 and VS to 17.9.2? Do you have another machine to cross check if you can compile the code?

**Comment by fotiDim** [comment]
@mortenboye the fact you were trying a release build was a key detail. Now, I finally managed to reproduce the issue (on Win 10 btw). We will have a look and hopefully a fix within the week.

**Comment by rohitsangwan01** [comment]
@mortenboye Please try with this https://github.com/Navideck/universal_ble/pull/16 pr

**Comment by mortenboye** [comment]
> @mortenboye Please try with this #16 pr

That works! Thank you.

**Comment by fotiDim** [comment]
@FlawLessx please try with the latest main and confirm that it works for you.
