### ISSUE TITLE
Disconnected peripherals disappear on Windows

### ISSUE THREAD

**Issue by BikeBr0** [Navideck/universal_ble#19]
I'm having trouble disconnecting from a BLE Peripheral. I am able to scan and connect to the peripheral but calling disconnect does not work as expected:

Steps to reproduce:

1) Use UniversalBle to scan and connect to a device on Windows
2) Confirmed with smartphone that device **does not** appear in bluetooth scans
3) Use UniversalBle to disconnect ()
4) Confirmed with smartphone that device **does** appear in bluetooth scans
5) Use UniversalBle to scan for devices

Result - BleDevice no longer available in UniversalBle scan results (nor from UniversalBle.getConnectedDevices)
Expected - BleDevice should appear in scan result

**Comment by rohitsangwan01** [comment]
@BikeBr0 After disconnected from UniversalBle, is that Ble peripheral also disconnected from Windows bluetooth settings, please cross check that
Also, verify if device is connected with: `UniversalBle.getConnectedDevices()` api

**Comment by BikeBr0** [comment]
It must be @rohitsangwan01  since it is accessible from my phone. And I checked with getConnectedDevices, it was not returned.

**Comment by rohitsangwan01** [comment]
@BikeBr0  ok so after disconnecting from UniversalBle
that devices appears in scan results from mobile
but not in windows ?

**Comment by BikeBr0** [comment]
Correct

**Comment by rohitsangwan01** [comment]
@BikeBr0 can you cross check with
https://apps.microsoft.com/detail/9n0ztkf1qd98?hl=en-US&gl=US
sometimes windows creates such issues

**Comment by BikeBr0** [comment]
Hang on, this seems to work as expected with my very simple test case. I'll do more digging and let you know more precisely what is causing the problem (if I can).

**Comment by BikeBr0** [comment]
All good @rohitsangwan01. I now see the bug in my own code.

**Comment by BikeBr0** [comment]
All good @rohitsangwan01. I now see the bug in my own code.
