### ISSUE TITLE
Adding universal_ble to pubspec.yaml results in Nuget.exe not found warning

### ISSUE THREAD

**Issue by BikeBr0** [Navideck/universal_ble#25]
Launching lib\main.dart on Windows in debug mode...
Nuget.exe not found, trying to download or use cached version.

**Comment by fotiDim** [comment]
Do builds fail for you, or is this just a warning?

**Comment by BikeBr0** [comment]
I had more information in the initial bug report but it seems to have vanished @fotiDim. This does not seem to be causing a build or runtime error.

**Comment by fotiDim** [comment]
Closing in favor of https://github.com/Navideck/universal_ble/issues/26
