### ISSUE TITLE
Access Denied when subscribing on windows?

### ISSUE THREAD

**Issue by JM3214** [Navideck/universal_ble#64]
I'm in the process of migrating a project from flutter_blue_plus to universal_ble so i can run it on windows. 
I get the following output when i build for windows, but seems to subscribe to characteristic data on Android just fine? 

The service is my own, running on arduino, all worked fine before switching, so I don't think its that. 

```
ConnectionLog: Device found
ConnectionLog: Device found
ConnectionLog: Services discovered
ConnectionLog: Services discovered
Failed to get characteristics for service: 4cc3c542-69b1-11ee-8c99-0242ac120003, With Status: AccessDenied
ConnectionLog: Connected
ConnectionLog: Connected
```
Any insight would be much appreciated! 
Thanks

**Comment by rohitsangwan01** [comment]
@JM3214 are you somehow making multiple connect calls parallely ?
Are you getting this error everytime you try to connect ?

**Comment by JM3214** [comment]
I don't think so, if it was, it would do the same on Android wouldn't it? 
Yes, same thing when connecting to any device on windows.

**Comment by rohitsangwan01** [comment]
> I don't think so, if it was, it would do the same on Android wouldn't it?

Android have different process of handling connection, Windows Winrt Api’s have more complications

> Yes, same thing when connecting to any device on windows.

Are you getting same behaviour in Example app ?
If yes, then please try once in [BluetoothLeExplorer](https://apps.microsoft.com/detail/9n0ztkf1qd98?rtc=1&hl=en-in&gl=IN)

**Comment by JM3214** [comment]
I think you are correct mate. I've got it sorted now, works very well!

**Comment by Erhannis** [comment]
@JM3214 I have a similar problem - what did you change to fix it?

**Comment by JM3214** [comment]
I was basically trying to connect to the same device multiple times, so just had to refactor a bit of stuff.
