### ISSUE TITLE
BLE Scanning Issue on iOS

### ISSUE THREAD

**Issue by alessandrodestefani** [Navideck/universal_ble#70]
I have trouble making the scanning work on IOS, i can't get any event on the scanning callback. The same code on Android and Windows is working perfectly. I have added the permission in the info.plist. 

The code:

UniversalBle.onScanResult = (event) {
      debugPrint("item found!");
};
await UniversalBle.startScan();

There is something that i am missing?

**Comment by rohitsangwan01** [comment]
@alessandrodestefani have you tried example app ?

**Comment by alessandrodestefani** [comment]
Ok, i have tried an empty project and also the example app.
I have found out that on IOS if you don't set   UniversalBle.onAvailabilityChange = (state) {};    the first commend startScan will not fire (the global queue will register it and will empty), the second time it will work.

If you have set onAvailabilityChange it will work fine.

**Comment by rohitsangwan01** [comment]
@alessandrodestefani please try with [this](https://github.com/Navideck/universal_ble/pull/103) PR

**Comment by fotiDim** [comment]
Released in [0.14.0](https://pub.dev/packages/universal_ble/versions/0.14.0)
