### ISSUE TITLE
Under android, you cannot connect again after three or five times of repeated connection and disconnection. status 257

### ISSUE THREAD

**Issue by liwuchao-cycmotor** [Navideck/universal_ble#77]
Under android, you cannot connect again after three or five times of repeated connection and disconnection. status 257.

D/BluetoothGatt(27725): connect() - device: F1:ED:FC:C3:10:A9, auto: false, eattSupport: false
D/BluetoothGatt(27725): registerApp()
D/BluetoothGatt(27725): registerApp() - UUID=6047c621-6d5b-4d96-95e6-5e0793674b62
D/BluetoothGatt(27725): onClientRegistered() - status=257 clientIf=0
D/UniversalBlePlugin(27725): onConnectionStateChange-> Status: 257, NewState: 0

**Comment by rohitsangwan01** [comment]
Its android limitation, we can't do anything about it,
Feel free to reopen..

**Comment by rohitsangwan01** [comment]
@liwuchao-cycmotor  Should be fixed in https://github.com/Navideck/universal_ble/pull/109/files

**Comment by fotiDim** [comment]
Released in [0.14.0](https://pub.dev/packages/universal_ble/versions/0.14.0)

**Comment by liwuchao-cycmotor** [comment]
Thank you very much!
