### ISSUE TITLE
requestMTU doesnt seem to be working on Windows

### ISSUE THREAD

**Issue by tototo23** [Navideck/universal_ble#82]
Hi,
First thanks for this awesome plugin :)

I'm having an issue when trying to increase the default MTU value to send data to a device, on windows : 
When I call the function `await UniversalBle.requestMtu(deviceId, requestedMTU)`, no matter the value of `requestedMTU` it always returns `65`.

When I checked the `cpp` source code (I'm not at all a c++ developper) i feel like the "expected_mtu" parameter is not used to set the MTU, and just returns the current value. Does it mean that it's not possible to change the MTU on Windows? Or maybe I missunderstood something?

Thank you

**Comment by rohitsangwan01** [comment]
@tototo23 its not possible to change MTU on Windows, so this method will just return the current MTU

From official docs :

> As a developer, you can't change the value used by Windows itself, since that's fully managed by the operating system.

https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattsession.maxpdusizechanged?view=winrt-22621
