### ISSUE TITLE
PlatformException(Failed, Failed to update subscription state, characteristic not found, null)

### ISSUE THREAD

**Issue by LeeBitCo** [Navideck/universal_ble#83]
need help!!!!!!
 universal_ble: ^0.12.0;

when  await UniversalBle.setNotifiable  get this error!

have permission and  await UniversalBle.discoverServices  also  requested!

**Comment by LeeBitCo** [comment]
Android  Platform!

**Comment by rohitsangwan01** [comment]
@LeeBitCo have you checked if the service is available in discoveredServices ?

**Comment by LeeBitCo** [comment]
> @LeeBitCo have you checked if the service is available in discoveredServices ?

thanks!!! it's fixed!
