### ISSUE TITLE
turn off Bluetooth

### ISSUE THREAD

**Issue by yangfeifei1994** [Navideck/universal_ble#90]
Could you provide a function to turn off Bluetooth on Windows? A function to turn on Bluetooth has already been designed.

**Comment by Silvesterrr** [comment]
Also waiting on that. (android + linux)

**Comment by rohitsangwan01** [comment]
Added disableBluetooth here https://github.com/Navideck/universal_ble/pull/113

**Comment by fotiDim** [comment]
Released in [0.14.0](https://pub.dev/packages/universal_ble/versions/0.14.0)
