### ISSUE TITLE
Windows Release build does not find devices.

### ISSUE THREAD

**Issue by johncharris** [Navideck/universal_ble#93]
I have a simple app that does a BLE scan and connects to a device and shows the value of an attribute. This works in debug mode, but when in Release no devices are found.  This is before any packaging. I'm trying to run it straight out of the release folder after it was built.

Any ideas?

**Comment by Wicz3k** [comment]
Did you try flutter clean?
Problem is only on windows?
Did you try example app?
Try share some code.

**Comment by johncharris** [comment]
I ran the example code, and it works fine so the problem is on my side. I'll update my code to be more like the example and post back if I find the issue.

**Comment by johncharris** [comment]
I've had no luck figuring this out. I published my code at https://github.com/johncharris/ble_temperture.

**Comment by rohitsangwan01** [comment]
@johncharris maybe add a try/catch block when calling start scan [here](https://github.com/johncharris/ble_temperture/blob/main/lib/devices_screen.dart#L49) in your code, and log that with your `addMessage` to cross check if startScan is failing somehow in release build

**Comment by Sravdar** [comment]
I had similar problem today. When app is first launched it said bluetooth is not enabled. When closed the bluetooth by hand and re-opened it started scaning.

I think on windows release builds when you open the executable `onAvailabilityChange` callback doesn't get called unlike the behaviour in debug mode. On initstate calling `UniversalBle.getBluetoothAvailabilityState();` fixed this problem.

**Comment by rohitsangwan01** [comment]
@Sravdar fixed in https://github.com/Navideck/universal_ble/pull/112

**Comment by fotiDim** [comment]
Released in [0.14.0](https://pub.dev/packages/universal_ble/versions/0.14.0)
